package View;

import Controller.AlgorithmController;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;

public class SavedAlgorithmsView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(View.SavedAlgorithmsView.class.getName());
    private AlgorithmController controller;
    private JFrame parentFrame;
      
    public SavedAlgorithmsView(AlgorithmController controller, JFrame parentFrame) {
        this.controller = controller;
        this.parentFrame = parentFrame;
        initComponents(); // NetBeans generated
        setupCustomComponents(); // Our setup
        setLocationRelativeTo(parentFrame);
    }
    
    public SavedAlgorithmsView() {
        initComponents();
        // Set button texts
        jButton2.setText("Create");
        jButton3.setText("Load"); 
        jButton4.setText("Edit");
        jButton5.setText("Delete");
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.addRow(new Object[]{"No saved algorithms", "", "", "", ""});
    }
    
    private void setupCustomComponents() {
        // Clear and load table data
        refreshTable();
    }

    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows
        
        if (controller != null) {
            String[] states = controller.getSavedStateNames();
            if (states.length > 0) {
                for (String name : states) {
                    // Get actual array data from controller if possible
                    String arrayStr = "[Sample Data]"; // Default
                    String dateStr = new Date().toString();
                    
                    model.addRow(new Object[]{name, "Bubble Sort", arrayStr, dateStr, "0"});
                }
            } else {
                model.addRow(new Object[]{"No saved examples", "", "", "", ""});
            }
        } else {
            // Demo data
            model.addRow(new Object[]{"Demo Example 1", "Bubble Sort", "[5, 3, 8, 1, 9]", "27/12/2025", "10"});
            model.addRow(new Object[]{"Demo Example 2", "Quick Sort", "[10, 7, 8, 9, 1]", "26/12/2025", "15"});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("<-- Back  ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 153, 255));
        jLabel7.setText("AlgoViz");

        jLabel1.setText("[ Admin ]");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(70, 70, 70))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("**Saved Algorithm Examples**");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Example Name", "Algorithm", "Array", "Created Date", "Steps"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Create");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Load");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(48, 48, 48)
                        .addComponent(jButton3)
                        .addGap(56, 56, 56)
                        .addComponent(jButton4)
                        .addGap(61, 61, 61)
                        .addComponent(jButton5))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(0, 61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // CREATE button
        String name = JOptionPane.showInputDialog(this, "Enter name for new algorithm example:");
        if (name != null && !name.trim().isEmpty()) {
            if (controller != null) {
                if (controller.validateStateName(name)) {
                    // Actually save a state
                    if (controller.saveCurrentStateWithName(name)) {
                        refreshTable();
                        JOptionPane.showMessageDialog(this, "Created: " + name);
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to create!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, 
                        "Invalid name! Use 3-20 letters/numbers only.");
                }
            } else {
                // Demo mode - just add to table
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(new Object[]{name, "Bubble Sort", "[1, 2, 3, 4, 5]", new Date().toString(), "0"});
                JOptionPane.showMessageDialog(this, "Demo: Created " + name);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // EDIT button
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            String oldName = (String) jTable1.getValueAt(selectedRow, 0);
            if (!oldName.equals("No saved examples")) {
                String newName = JOptionPane.showInputDialog(this, "Enter new name:", oldName);
                if (newName != null && !newName.trim().isEmpty()) {
                    if (controller != null) {
                        if (controller.validateStateName(newName)) {
                            if (controller.updateState(oldName, newName)) {
                                jTable1.setValueAt(newName, selectedRow, 0);
                                JOptionPane.showMessageDialog(this, "Updated: " + oldName + " → " + newName);
                            } else {
                                JOptionPane.showMessageDialog(this, "Update failed!");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Invalid new name!");
                        }
                    } else {
                        // Demo mode
                        jTable1.setValueAt(newName, selectedRow, 0);
                        JOptionPane.showMessageDialog(this, "Demo: Updated name");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Cannot edit placeholder");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an example first.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // LOAD button
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            String name = (String) jTable1.getValueAt(selectedRow, 0);
        
            if (controller != null) {
                try {
                    // 1. LOAD the state into controller
                    controller.loadSavedState(name);
                
                    // 2. Open NEW VisualizationView
                    VisualizationView newViz = new VisualizationView();
                
                    // 3. CRITICAL: Pass the SAME controller instance
                    // We need to modify VisualizationView to accept controller
                    newViz.setController(controller);
                
                    // 4. Show and close
                    newViz.setVisible(true);
                    this.dispose();
                
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, 
                        "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // DELETE button
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            String name = (String) jTable1.getValueAt(selectedRow, 0);
            if (!name.equals("No saved examples")) {
                int confirm = JOptionPane.showConfirmDialog(this,
                    "Delete example '" + name + "'?\nThis cannot be undone!",
                    "Confirm Delete", 
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);
                
                if (confirm == JOptionPane.YES_OPTION) {
                    if (controller != null) {
                        if (controller.deleteSavedState(name)) {
                            refreshTable();
                            JOptionPane.showMessageDialog(this, "Deleted: " + name);
                        } else {
                            JOptionPane.showMessageDialog(this, "Delete failed!");
                        }
                    } else {
                        // Demo mode
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        model.removeRow(selectedRow);
                        JOptionPane.showMessageDialog(this, "Demo: Deleted " + name);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Cannot delete placeholder");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an example first.");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SavedAlgorithmsView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
