/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AlgorithmController;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import java.util.Arrays;

/** 
 *
 * @author Asus
 */

public class VisualizationView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VisualizationView.class.getName());

    private VisualizationPanel visualizationPanel;
    private AlgorithmController controller;

    public VisualizationView() {
        initComponents();

        // 1. Create panel FIRST
        visualizationPanel = new VisualizationPanel();
        
        // 2. Create controller WITH the panel
        controller = new AlgorithmController(visualizationPanel);
        
        // 3. Add panel to UI
        jPanel5.setLayout(new BorderLayout());
        jPanel5.add(visualizationPanel, BorderLayout.CENTER);
        
        // Update button text
        jButton8.setText("Manage States");
        
        // Center window
        setLocationRelativeTo(null);
    }
    
    public void setController(AlgorithmController controller) {
        this.controller = controller;
    
        // Update visualization with loaded array
        if (controller != null && visualizationPanel != null) {
            int[] loadedArray = controller.getArray();
            visualizationPanel.setArray(loadedArray);
        
            // Update display field
            updateArrayField();
        
            if (jButton2 != null) {
            jButton2.setEnabled(true); // Enable Play button
            }
        }
    }
    
    public void setVisualizationPanel(VisualizationPanel panel) {
        this.visualizationPanel = panel;
    
        // Remove existing panel and add new one
        jPanel5.removeAll();
        jPanel5.setLayout(new BorderLayout());
        jPanel5.add(panel, BorderLayout.CENTER);
        jPanel5.revalidate();
        jPanel5.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("<-- Back  ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("[ Admin ]");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 153, 255));
        jLabel7.setText("AlgoViz");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("**Bubble Sort Visualization**");

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Play");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Pause");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Stop");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Speed");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(126, 126, 126))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Array :");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setText("jTextField1");

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setText("Randomize");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(146, 146, 146))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel5.setForeground(new java.awt.Color(204, 204, 204));

        jLabel5.setText("**Visualization Area**");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Step : 0");

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setText("Save State");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setText("Statistic");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(66, 66, 66)
                .addComponent(jButton7)
                .addGap(74, 74, 74)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Back button - close this window
        new HomeView().setVisible(true);
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Play button
        if (controller != null) {
            controller.playBubbleSort();
            updateStepLabel("Playing...");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Reset button
        if (controller != null) {
            controller.reset();
            updateArrayField();
            updateStepLabel("0");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Randomize button
        if (controller != null) {
            controller.randomize();
            updateArrayField();
            updateStepLabel("0");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Pause button
        if (controller != null) {
            controller.pause();
            updateStepLabel("Paused");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Stop button
        if (controller != null) {
            controller.stop();
            updateStepLabel("Stopped");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // ================== SAVE STATE WITH VALIDATION ==================
        if (controller == null) {
            JOptionPane.showMessageDialog(this, "Controller not initialized!", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        String name = JOptionPane.showInputDialog(this, 
            "Enter a name for this state (3-20 characters, letters/numbers only):", 
            "Save Current State", 
            JOptionPane.PLAIN_MESSAGE);
    
        // VALIDATION 1: Check if user cancelled
        if (name == null) {
            return; // User cancelled
        }
    
        name = name.trim();
    
        // VALIDATION 2: Check if empty
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Name cannot be empty!", 
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        // VALIDATION 3: Check length
        if (name.length() < 3 || name.length() > 20) {
            JOptionPane.showMessageDialog(this, 
                "Name must be 3-20 characters!", 
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        // VALIDATION 4: Check for invalid characters
        if (!name.matches("^[a-zA-Z0-9_\\-\\s]+$")) {
            JOptionPane.showMessageDialog(this, 
                "Name can only contain letters, numbers, spaces, hyphens, and underscores!",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        // VALIDATION 5: Check if array is empty
        int[] currentArray = visualizationPanel.getArray();
        if (currentArray == null || currentArray.length == 0) {
            JOptionPane.showMessageDialog(this, 
                "Cannot save empty array!", 
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        // VALIDATION 6: Check for duplicate name
        String[] existingStates = controller.getSavedStateNames();
        boolean exists = false;
            for (String state : existingStates) {
            if (state.equalsIgnoreCase(name)) {
                exists = true;
                break;
            }
        }
    
        if (exists) {
            int overwrite = JOptionPane.showConfirmDialog(this,
                "A state named '" + name + "' already exists. Overwrite?",
                "Confirm Overwrite",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        
            if (overwrite != JOptionPane.YES_OPTION) {
                return;
            }
        }
    
        // All validation passed - save the state
        try {
            // DEBUG: Show what we're saving
            System.out.println("=== SAVING STATE ===");
            System.out.println("Name: " + name);
            System.out.println("Array: " + java.util.Arrays.toString(currentArray));
            System.out.println("Controller: " + controller);
        
            boolean success = controller.saveCurrentStateWithName(name);
        
            if (success) {
                JOptionPane.showMessageDialog(this, 
                    "✅ State saved successfully as: " + name, 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
            
                // Update display
                updateArrayField();
            
                // Debug: Check if saved
                System.out.println("✅ Save successful!");
                System.out.println("Total saved states: " + controller.getSavedStateNames().length);
            
                } else {
                JOptionPane.showMessageDialog(this, 
                    "❌ Save failed! Controller returned false.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                System.err.println("❌ Controller.saveCurrentStateWithName() returned false");
            }
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "❌ Error saving state: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            System.err.println("❌ Exception during save: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // ================== MANAGE STATES (CRUD MENU) ==================
        if (controller == null) {
            JOptionPane.showMessageDialog(this, "Controller not initialized!", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String[] savedStates = controller.getSavedStateNames();
        
        // VALIDATION: Check if there are any saved states
        if (savedStates.length == 0) {
            JOptionPane.showMessageDialog(this, 
                "No saved states found. Save a state first!", 
                "Info", 
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        // Create a dialog with CRUD options
        String[] options = {"📂 Load State", "✏️ Rename State", "🗑️ Delete State", "📋 List All States", "❌ Cancel"};
        int choice = JOptionPane.showOptionDialog(this,
            "Select operation to perform:", 
            "Manage Saved States",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            options,
            options[0]);
        
        switch (choice) {
            case 0: // Load State
                String selectedToLoad = (String) JOptionPane.showInputDialog(this,
                    "Select state to load:", 
                    "Load State",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    savedStates,
                    savedStates[0]);
                
                if (selectedToLoad != null) {
                    // VALIDATION: Check if state still exists
                    boolean stateExists = false;
                    for (String state : controller.getSavedStateNames()) {
                        if (state.equals(selectedToLoad)) {
                            stateExists = true;
                            break;
                        }
                    }
                    
                    if (!stateExists) {
                        JOptionPane.showMessageDialog(this, 
                            "State no longer exists: " + selectedToLoad, 
                            "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    
                    controller.loadSavedState(selectedToLoad);
                    updateArrayField();
                    updateStepLabel("Loaded: " + selectedToLoad);
                    JOptionPane.showMessageDialog(this, 
                        "Successfully loaded: " + selectedToLoad, 
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                }
                break;
                
            case 1: // Rename State (UPDATE)
                String selectedToRename = (String) JOptionPane.showInputDialog(this,
                    "Select state to rename:", 
                    "Rename State",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    savedStates,
                    savedStates[0]);
                
                if (selectedToRename != null) {
                    String newName = JOptionPane.showInputDialog(this,
                        "Enter new name for '" + selectedToRename + "':",
                        selectedToRename);
                    
                    if (newName != null && !newName.trim().isEmpty()) {
                        newName = newName.trim();
                        
                        // VALIDATION for new name
                        if (newName.length() < 3 || newName.length() > 20) {
                            JOptionPane.showMessageDialog(this, 
                                "New name must be 3-20 characters!", 
                                "Validation Error", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                        
                        if (!newName.matches("^[a-zA-Z0-9_\\-\\s]+$")) {
                            JOptionPane.showMessageDialog(this, 
                                "Invalid characters in new name!",
                                "Validation Error", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                        
                        // Check if new name already exists (excluding current)
                        boolean duplicate = false;
                        for (String state : savedStates) {
                            if (state.equals(newName) && !state.equals(selectedToRename)) {
                                duplicate = true;
                                break;
                            }
                        }
                        
                        if (duplicate) {
                            JOptionPane.showMessageDialog(this, 
                                "Name '" + newName + "' already exists!",
                                "Validation Error", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                        
                        // Update the state
                        // You need to add updateState(oldName, newName) to your controller
                        // For now, we'll show a message
                        JOptionPane.showMessageDialog(this, 
                            "Rename functionality to be implemented in controller.\n" +
                            "Would rename: " + selectedToRename + " → " + newName,
                            "Info", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                break;
                
            case 2: // Delete State
                String selectedToDelete = (String) JOptionPane.showInputDialog(this,
                    "Select state to delete:", 
                    "Delete State",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    savedStates,
                    savedStates[0]);
                
                if (selectedToDelete != null) {
                    // VALIDATION: Confirmation with warning
                    int confirm = JOptionPane.showConfirmDialog(this,
                        "WARNING: This action cannot be undone!\n" +
                        "Delete state '" + selectedToDelete + "'?",
                        "Confirm Delete",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE);
                    
                    if (confirm == JOptionPane.YES_OPTION) {
                        try {
                            controller.deleteSavedState(selectedToDelete);
                            JOptionPane.showMessageDialog(this, 
                                "Successfully deleted: " + selectedToDelete, 
                                "Success", JOptionPane.INFORMATION_MESSAGE);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, 
                                "Error deleting state: " + e.getMessage(), 
                                "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
                break;
                
            case 3: // List All States
                StringBuilder list = new StringBuilder("Saved States (" + savedStates.length + "):\n\n");
                for (int i = 0; i < savedStates.length; i++) {
                    list.append(i + 1).append(". ").append(savedStates[i]).append("\n");
                }
                JOptionPane.showMessageDialog(this, 
                    list.toString(), 
                    "All Saved States", 
                    JOptionPane.INFORMATION_MESSAGE);
                break;
                
            default: // Cancel or closed dialog
                // Do nothing
                break;
        }
    }//GEN-LAST:event_jButton8ActionPerformed
    
    // ================== YOUR HELPER METHODS ==================
    
    private void updateStepLabel(String text) {
        jLabel6.setText("Step: " + text);
    }
    
    private void updateArrayField() {
        if (controller != null && visualizationPanel != null) {
            int[] array = visualizationPanel.getArray();
            if (array != null && array.length > 0) {
                // Show first 5 elements for brevity
                if (array.length > 5) {
                    jTextField1.setText(Arrays.toString(Arrays.copyOfRange(array, 0, 5)) + "...");
                } else {
                    jTextField1.setText(Arrays.toString(array));
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VisualizationView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
